#!/usr/bin/env node
/**
 * Syncs GOOGLE_MAPS_API_KEY from .env into generated, gitignored native/JS config.
 * Never writes secrets into tracked files (Info.plist, etc.).
 *
 * Outputs:
 *   - src/constants/env.generated.ts (JS)
 *   - ios/Plarem/GoogleMapsApiKey.plist (iOS bundle resource, gitignored)
 *
 * Android reads .env at Gradle build time (android/app/build.gradle).
 */
const fs = require('fs');
const path = require('path');
const { loadEnv } = require('./load-env');

const key = loadEnv().GOOGLE_MAPS_API_KEY?.trim() ?? '';
const version = require(path.join(__dirname, '..', 'package.json')).version;
const jsConfigPath = path.join(__dirname, '..', 'src', 'constants', 'env.generated.ts');
const iosSecretsPlistPath = path.join(__dirname, '..', 'ios', 'Plarem', 'GoogleMapsApiKey.plist');
const pbxprojPath = path.join(__dirname, '..', 'ios', 'Plarem.xcodeproj', 'project.pbxproj');

fs.writeFileSync(
  jsConfigPath,
  `// This file is generated by scripts/sync-env.js. Do not edit by hand.\n` +
    `export const GOOGLE_MAPS_API_KEY = ${JSON.stringify(key)};\n` +
    `export const APP_VERSION = ${JSON.stringify(version)};\n`,
);

if (fs.existsSync(path.join(__dirname, '..', 'ios'))) {
  const iosPlist =
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n` +
    `<plist version="1.0">\n<dict>\n` +
    `\t<key>GOOGLE_MAPS_API_KEY</key>\n\t<string>${key}</string>\n` +
    `</dict>\n</plist>\n`;
  fs.writeFileSync(iosSecretsPlistPath, iosPlist);
}

if (fs.existsSync(pbxprojPath)) {
  const pbxproj = fs.readFileSync(pbxprojPath, 'utf8');
  const stamped = pbxproj.replace(/MARKETING_VERSION = [^;]+;/g, `MARKETING_VERSION = ${version};`);
  if (stamped !== pbxproj) {
    fs.writeFileSync(pbxprojPath, stamped);
  }
}

if (!key) {
  console.warn(
    'No GOOGLE_MAPS_API_KEY in .env — maps and place search will not work until you add one.',
  );
} else {
  console.log(`Synced GOOGLE_MAPS_API_KEY and version ${version} to generated config (not committed).`);
}
