#!/usr/bin/env node
/**
 * Syncs GOOGLE_MAPS_API_KEY from .env into iOS Info.plist for native map rendering,
 * and stamps the app version from package.json (the single source of truth) into
 * the generated JS config and the iOS project (MARKETING_VERSION). Android reads
 * package.json directly during Gradle builds (see android/app/build.gradle).
 */
const fs = require('fs');
const path = require('path');
const { loadEnv } = require('./load-env');

const key = loadEnv().GOOGLE_MAPS_API_KEY?.trim() ?? '';
const version = require(path.join(__dirname, '..', 'package.json')).version;
const jsConfigPath = path.join(__dirname, '..', 'src', 'constants', 'env.generated.ts');
const plistPath = path.join(__dirname, '..', 'ios', 'Plarem', 'Info.plist');
const pbxprojPath = path.join(__dirname, '..', 'ios', 'Plarem.xcodeproj', 'project.pbxproj');

// Always generate a JS/TS module so the bundler can read the values
// without relying on a Babel env plugin.
fs.writeFileSync(
  jsConfigPath,
  `// This file is generated by scripts/sync-env.js. Do not edit by hand.\n` +
    `export const GOOGLE_MAPS_API_KEY = ${JSON.stringify(key)};\n` +
    `export const APP_VERSION = ${JSON.stringify(version)};\n`,
);

// iOS: MARKETING_VERSION feeds CFBundleShortVersionString in Info.plist.
if (fs.existsSync(pbxprojPath)) {
  const pbxproj = fs.readFileSync(pbxprojPath, 'utf8');
  const stamped = pbxproj.replace(/MARKETING_VERSION = [^;]+;/g, `MARKETING_VERSION = ${version};`);
  if (stamped !== pbxproj) {
    fs.writeFileSync(pbxprojPath, stamped);
  }
}

if (!fs.existsSync(plistPath)) {
  process.exit(0);
}

let plist = fs.readFileSync(plistPath, 'utf8');
const entry = `\t<key>GOOGLE_MAPS_API_KEY</key>\n\t<string>${key}</string>\n`;

if (plist.includes('<key>GOOGLE_MAPS_API_KEY</key>')) {
  plist = plist.replace(
    /\t<key>GOOGLE_MAPS_API_KEY<\/key>\s*\n\t<string>[^<]*<\/string>\s*\n/,
    entry,
  );
} else {
  plist = plist.replace('</dict>\n</plist>', `${entry}</dict>\n</plist>`);
}

fs.writeFileSync(plistPath, plist);

if (!key) {
  console.warn(
    'No GOOGLE_MAPS_API_KEY in .env — maps and place search will not work until you add one.',
  );
} else {
  console.log(`Synced GOOGLE_MAPS_API_KEY and version ${version} to native Android/iOS and JS config.`);
}
