#!/usr/bin/env node
/**
 * Syncs GOOGLE_MAPS_API_KEY from .env into iOS Info.plist for native map rendering.
 * Android reads .env directly during Gradle builds; JS reads it via react-native-dotenv.
 */
const fs = require('fs');
const path = require('path');
const { loadEnv } = require('./load-env');

const key = loadEnv().GOOGLE_MAPS_API_KEY?.trim() ?? '';
const jsConfigPath = path.join(__dirname, '..', 'src', 'constants', 'env.generated.ts');
const plistPath = path.join(__dirname, '..', 'ios', 'Plarem', 'Info.plist');

// Always generate a JS/TS module so the bundler can read the key
// without relying on a Babel env plugin.
fs.writeFileSync(
  jsConfigPath,
  `// This file is generated by scripts/sync-env.js. Do not edit by hand.\n` +
    `export const GOOGLE_MAPS_API_KEY = ${JSON.stringify(key)};\n`,
);

if (!fs.existsSync(plistPath)) {
  process.exit(0);
}

let plist = fs.readFileSync(plistPath, 'utf8');
const entry = `\t<key>GOOGLE_MAPS_API_KEY</key>\n\t<string>${key}</string>\n`;

if (plist.includes('<key>GOOGLE_MAPS_API_KEY</key>')) {
  plist = plist.replace(
    /\t<key>GOOGLE_MAPS_API_KEY<\/key>\s*\n\t<string>[^<]*<\/string>\s*\n/,
    entry,
  );
} else {
  plist = plist.replace('</dict>\n</plist>', `${entry}</dict>\n</plist>`);
}

fs.writeFileSync(plistPath, plist);

if (!key) {
  console.warn(
    'No GOOGLE_MAPS_API_KEY in .env — maps and place search will not work until you add one.',
  );
} else {
  console.log('Synced GOOGLE_MAPS_API_KEY to native Android/iOS and JS config.');
}
